### ISSUE TITLE
Order the enums the same way

### ISSUE THREAD

**Issue by kenchris** [diekus/fold-angle#12]
![image](https://user-images.githubusercontent.com/1101339/84148993-0d99ff80-aa60-11ea-8886-c5e005b0a4de.png)

![image](https://user-images.githubusercontent.com/1101339/84149010-138fe080-aa60-11ea-8786-ba599d730da2.png)

![image](https://user-images.githubusercontent.com/1101339/84149020-18ed2b00-aa60-11ea-8871-6d55159e7547.png)

**Comment by diekus** [comment]
![image](https://user-images.githubusercontent.com/3104648/84150404-bd1fa380-aa59-11ea-8f5d-22ed2866171c.png)
ordered
