### ISSUE TITLE
What does ]0-110[ landscape-primary etc map to?

### ISSUE THREAD

**Issue by kenchris** [diekus/fold-angle#24]
Not book or laptop according to the below:

![image](https://user-images.githubusercontent.com/1101339/84317267-ca798280-ab6c-11ea-9b72-d3afe752c0c4.png)

**Comment by diekus** [comment]
fixed postures and angles based on postures for other devices coming out
![image](https://user-images.githubusercontent.com/3104648/85536849-5da1c600-b60b-11ea-8bdc-20688cd5d56b.png)
