### ISSUE TITLE
Explain in introduction the target form factors

### ISSUE THREAD

**Issue by anssiko** [diekus/fold-angle#26]
This could include:
- a device with a screen that physically folds (aka foldable device)
- a device with two internal screens separated by a physical hinge (aka dual-screen device)

The prose suggest both are considered, so it'd be good to make this clear in the introduction.

https://diek.us/fold-angle/#introduction

**Comment by diekus** [comment]
That's actually a great suggestion to make the spec more clear. It might not be obvious to many people what a 'foldable' consists of, and even if it's clear, I've seen many conflicting definitions of them. I will add an explanation to better scope out line of work!   

![form-factors](https://user-images.githubusercontent.com/3104648/84670090-8ba54d00-af1d-11ea-92c7-87721b6a8b47.png)

**Comment by anssiko** [comment]
The updated introduction looks great to me. Thanks!
