### ISSUE TITLE
Don't say approximately

### ISSUE THREAD

**Issue by kenchris** [diekus/fold-angle#28]
We can extend this

> The posture values table shows how the posture values are derived depending on the orientation of the fold:

with

The values are approximations and might differ per device. For instance, a device might not yield exactly 180° when laying flat, but instead values ranging from 175° to 185°. Device makers SHOULD make sure that the physical device postures map correctly to the postures defined by this specification.

Some devices might also lack one or more of the postures due to physical constraints or device design, in which case the device SHOULD make sure that all combinations of angles and device orientation (which can be locked by [[SCREEN-ORIENTATION]] and host OS) maps into one of the defined postures.

@anssik

**Comment by diekus** [comment]
updated table and values 
![Uploading image.png…]()
