### ISSUE TITLE
Add link to the polyfill and explainer

### ISSUE THREAD

**Issue by anssiko** [diekus/fold-angle#32]
You could link to the polyfill and/or explainer from the spec header using https://github.com/w3c/respec/wiki/otherLinks to make these complementary resources more visible.

**Comment by diekus** [comment]
![image](https://user-images.githubusercontent.com/3104648/86025796-8caea200-ba26-11ea-9b56-19c353d56794.png)

links to additional resources added

**Comment by anssiko** [comment]
Thanks!
